Added mod_actions reason aliases
ZeppelinBot/Zeppelin pull request #296
Opened 2021-09-23 10:00 UTC by metal0

2021-09-23 10:50 UTC, almeidx requested changes

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/parseReason.ts
> +    reason = reason!.substring(0, MAX_REASON_LENGTH - 6) + " [...]";
```suggestion
    reason = reason!.substring(0, MAX_REASON_LENGTH - 4) + " […]";
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/UnbanCmd.ts
> +    const reason = parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]));
```suggestion
    const reason = formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()]);
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/parseReason.ts
> +export function parseReason(config: any, reason: string): string {
There has to be a way to type the `config` argument here

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/parseReason.ts
> +    reason = config.reason_aliases![reason.toLowerCase()] ?? reason;
I can't imagine the `!` being needed here
```suggestion
    reason = config.reason_aliases[reason.toLowerCase()] ?? reason;
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/parseReason.ts
> +    reason = config.reason_aliases![reason.toLowerCase()] ?? reason;
If you're making the `reason` lowercase here, you should make the `reason_aliases` keys lowercase too

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/actualUnmuteUserCmd.ts
> +    ? parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]))
```suggestion
    ? formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()])
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/actualMuteUserCmd.ts
> +    ? parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]))
```suggestion
    ? formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()])
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/actualKickMemberCmd.ts
> +  const reason = parseReason(config, formatReasonWithAttachments(args.reason, msg.attachments));
Also, if `msg` is a Message from discord.js, this won't work. (`msg` is typed as any so I don't really know)

```suggestion
  const reason = formatReasonWithAttachments(parseReason(config, args.reason), msg.attachments);
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/WarnCmd.ts
> +    const reason = parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]));
```suggestion
    const reason = formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()]);
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/MassmuteCmd.ts
> +    );
```suggestion
    const muteReason = formatReasonWithAttachments(
      parseReason(config, muteReasonReceived.content),
      [...msg.attachments.values()],
    );
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/MassUnbanCmd.ts
> +    );
```suggestion
    const unbanReason = formatReasonWithAttachments(
      parseReason(config, unbanReasonReply.content),
      [...msg.attachments.values()],
    );
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/ForcebanCmd.ts
> +    const reason = parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]));
```suggestion
    const reason = formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()]);
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/commands/AddCaseCmd.ts
> +    const reason = parseReason(config, formatReasonWithAttachments(args.reason, [...msg.attachments.values()]));
```suggestion
    const reason = formatReasonWithAttachments(parseReason(config, args.reason), [...msg.attachments.values()]);
```

2021-09-23 10:50 UTC, almeidx commented on backend/src/plugins/ModActions/functions/banUserId.ts
> +  if (reason) reason = parseReason(config, reason);
```suggestion
  reason &&= parseReason(config, reason);
```

2021-09-23 19:46 UTC, almeidx requested changes

2021-09-23 19:49 UTC, almeidx requested changes

2021-09-23 19:49 UTC, almeidx commented on backend/src/plugins/ModActions/functions/actualKickMemberCmd.ts
> +import { GuildMessage } from "knub/dist/types";
```suggestion
```

2022-06-02 16:19 UTC, isaacKenyon commented
> ```yaml
> plugins:
>   mod_actions:
>    reason_aliases:
>      advertising: This is an alias for advertising
> ```
> 
> > `!ban @user advertising`
> 
> The `reason_aliases` keys are not case sensitive

`reason_aliases` should be nested under the `config:`

2022-06-26 16:36 UTC, Ibotmealot commented
Dunno if this isn't intended, however, when using the update command and if you use an aliases it doesn't display the aliases. Hope that makes sense?

2023-02-27 10:14 UTC, metal0 commented
Superded by #390

2023-02-27 10:14 UTC, closed without merging