fix createCase() user id stuff
ZeppelinBot/Zeppelin pull request #317
Opened 2022-01-25 19:31 UTC by almeidx

2022-01-25 19:36 UTC, metal0 approved these changes

2022-01-25 19:40 UTC, metal0 requested changes

2022-01-25 19:40 UTC, metal0 commented on backend/src/plugins/Cases/functions/createCase.ts
> +  if (args.reason || args.noteDetails?.length) {
u suck

2022-01-25 20:25 UTC, almeidx commented on backend/src/plugins/Cases/functions/createCase.ts
> +  if (args.reason || args.noteDetails?.length) {
![image](https://user-images.githubusercontent.com/42935195/151053985-73d93a04-7e99-420d-afab-6d95eab6626f.png)

2022-01-26 09:35 UTC, metal0 approved these changes
lgtm

2022-04-21 19:28 UTC, merged