Moderation Guide
ZeppelinBot/Zeppelin pull request #356
Opened 2022-07-17 01:03 UTC by isaacKenyon

This guide aims to somewhat complete the currently WIP state of https://zeppelin.gg/docs/setup-guides/moderation .
Happy to implement more example tabs in corrospondence to the text under each header.

It focuses on the setup of the `mod_actions` plugin, but it can be extended to focus on the command side too.

2022-07-17 01:05 UTC, isaacKenyon commented
[Signed](https://github.com/ZeppelinBot/CLA/pull/24).

2023-12-28 12:31 UTC, metal0 commented
@cla-bot check

2023-12-28 12:33 UTC, metal0 commented on dashboard/src/components/docs/Moderation.vue
> +      <a href="https://docs.google.com/presentation/d/e/2PACX-1vQTFZW4NiJicngfAv36tLlWG5XjktVyZhljekOkzUyzsktwcNCH_Zm82Dm3r1c7S7vKOArJ6XIO5azC/pub?start=true&loop=false&delayms=60000&slide=id.gc6f9e4
Can we remove & reword this section for the time being? DEX's handbook is no longer available and needs remaking

2023-12-28 12:34 UTC, metal0 requested changes
Reword handbook section

2023-12-29 05:38 UTC, metal0 approved these changes

2023-12-29 06:00 UTC, zayKenyon commented
he tried to take credit 😤

2023-12-29 13:56 UTC, almeidx requested changes

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +        <router-link to="/docs/plugins/modactions"> Mod actions</router-link>
Let's move the extra space in the beginning outside of the `router-link` component

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +        <router-link to="/docs/plugins/mutes">Mutes</router-link> plugin.
```suggestion
        <router-link to="/docs/plugins/mutes">Mutes</router-link> plugin for that.
```

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +          permissions </router-link>work before reading this guide since
```suggestion
          permissions</router-link> work before reading this guide since
```

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +        the configs defined here rely on your these concepts.
There are some grammar issues here

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +      moderator role Id in the config, assign it a level (50), and enable the
```suggestion
      moderator role id in the config, assign it a level (50), and enable the
```

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +      and <code>message_on_ban</code> to true (enabling them), then assign a
This is already implied by the start of the sentence ("To enable this feature")
```suggestion
      and <code>message_on_ban</code> to true, then assign a
```

2023-12-29 13:56 UTC, almeidx commented on dashboard/src/components/docs/Moderation.vue
> +    Employing what we have learnt so far, we can write a configuration that:
Why isn't this wrapped in a paragraph tag?

2023-12-30 22:08 UTC, almeidx approved these changes

2023-12-30 22:09 UTC, merged