fix: crash when the arr argument for concatArr isn't specified
ZeppelinBot/Zeppelin pull request #378
Opened 2023-01-09 13:32 UTC by rubyowo

2023-01-09 13:33 UTC, rubyowo commented
https://github.com/ZeppelinBot/CLA/pull/29

2023-01-09 15:45 UTC, almeidx requested changes

2023-01-09 15:45 UTC, almeidx commented on backend/src/templateFormatter.ts
> +    if(!arr) return "";
```suggestion
    if (!Array.isArray(arr)) return "";
```

2023-01-09 15:55 UTC, rubyowo commented on backend/src/templateFormatter.ts
> +    if(!arr) return "";
thx

2023-01-09 16:52 UTC, almeidx requested changes

2023-01-09 16:52 UTC, almeidx commented on backend/src/templateFormatter.ts
> +    if(!Array.isArray(arr)) return "";
```suggestion
    if (!Array.isArray(arr)) return "";
```

2023-07-01 11:01 UTC, Dragory commented
@cla-bot check

2023-11-18 10:51 UTC, merged