Update DJS + Display names fixes
ZeppelinBot/Zeppelin pull request #436
Opened 2023-11-26 14:10 UTC by metal0

Solves:
- https://linear.app/zeppelinbot/issue/ZDEV-39/match-visible-names-doesnt-match-display-names

2023-11-26 16:24 UTC, almeidx requested changes

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Automod/triggers/roleRemoved.ts
> +    const memberName = `**${renderUsername(member.user)}** (\`${member.id}\`)`;
```suggestion
    const memberName = `**${renderUsername(member)}** (\`${member.id}\`)`;
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/BotControl/commands/ServersCmd.ts
> +          )}** \`${owner.id}\`)`;
```suggestion
          return `\`${paddedId}\` **${g.name}** (${g.memberCount} members) (owner **${renderUsername(owner)}** \`${owner.id}\`)`;
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Cases/functions/createCase.ts
> +  const userName = renderUsername(user.username, user.discriminator);
"userName" :cringe:
```suggestion
  const userName = renderUsername(user);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Cases/functions/createCase.ts
> +  const modName = renderUsername(mod.username, mod.discriminator);
```suggestion
  const modName = renderUsername(mod);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Cases/functions/createCase.ts
> +    ppName = renderUsername(pp.username, pp.discriminator);
```suggestion
    ppName = renderUsername(pp);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/commands/CasesModCmd.ts
> +    const modName = mod instanceof User ? renderUsername(mod) : modId;
This doesn't account for GuildMember, maybe check the opposite instead (you have to import it)
```suggestion
    const modName = mod instanceof UnknownUser ? modId : renderUsername(mod);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/commands/CasesModCmd.ts
> +            icon_url: mod instanceof User || mod instanceof GuildMember ? mod.displayAvatarURL() : undefined,
```suggestion
            icon_url: mod instanceof UnknownUser ? undefined : mod.displayAvatarURL(),
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/commands/CasesModCmd.ts
> +import { APIEmbed, GuildMember, User } from "discord.js";
```suggestion
import { APIEmbed, User } from "discord.js";
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/commands/CasesUserCmd.ts
> +    if (!user.id || user instanceof UnknownUser) {
Should be enough
```suggestion
    if (user instanceof UnknownUser) {
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/events/PostAlertOnMemberJoinEvt.ts
> +        `<@!${member.id}> (${renderUsername(member.user)} \`${member.id}\`) joined with ${
```suggestion
        `<@!${member.id}> (${renderUsername(member)} \`${member.id}\`) joined with ${
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/commands/WarnCmd.ts
> +      `Warned **${renderUsername(memberToWarn.user)}** (Case #${warnResult.case.case_number})${messageResultText}`,
```suggestion
      `Warned **${renderUsername(memberToWarn)}** (Case #${warnResult.case.case_number})${messageResultText}`,
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ModActions/functions/actualKickMemberCmd.ts
> +  let response = `Kicked **${renderUsername(memberToKick.user)}** (Case #${kickResult.case.case_number})`;
```suggestion
  let response = `Kicked **${renderUsername(memberToKick)}** (Case #${kickResult.case.case_number})`;
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Mutes/commands/MutesCmd.ts
> +        return `<@!${member.id}> (**${renderUsername(member.user)}**, \`${member.id}\`)   🔧 Manual mute`;
```suggestion
        return `<@!${member.id}> (**${renderUsername(member)}**, \`${member.id}\`)   🔧 Manual mute`;
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Mutes/commands/MutesCmd.ts
> +        const username = user ? renderUsername(user) : "Unknown#0000";
```suggestion
        const username = renderUsername(user);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/ReactionRoles/util/addMemberPendingRoleChange.ts
> +            logger.warn(`Failed to apply role changes to ${renderUsername(member.user)} (${member.id}): ${e.message}`);
Pretty sure there is a "renderUserInfo()" function somewhere that renders "${tag} ($i{d})"
```suggestion
            logger.warn(`Failed to apply role changes to ${renderUsername(member)} (${member.id}): ${e.message}`);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Starboard/util/createStarboardEmbedFromMessage.ts
> +  embed.author.icon_url = (msg.member || msg.author).displayAvatarURL();
```suggestion
  embed.author.icon_url = (msg.member ?? msg.author).displayAvatarURL();
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/AvatarCmd.ts
> +    const user = args.user || msg.member || msg.author;
```suggestion
    const user = args.user ?? msg.member ?? msg.author;
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/LevelCmd.ts
> +    message.channel.send(`The permission level of ${renderUsername(member.user)} is **${level}**`);
```suggestion
    message.channel.send(`The permission level of ${renderUsername(member)} is **${level}**`);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/VcdisconnectCmd.ts
> +      `**${renderUsername(args.member.user)}** disconnected from **${channel.name}**`,
```suggestion
      `**${renderUsername(args.member)}** disconnected from **${channel.name}**`,
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/VcmoveCmd.ts
> +    sendSuccessMessage(pluginData, msg.channel, `**${renderUsername(args.member.user)}** moved to **${channel.name}**`);
```suggestion
    sendSuccessMessage(pluginData, msg.channel, `**${renderUsername(args.member)}** moved to **${channel.name}**`);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/VcmoveCmd.ts
> +          `Failed to move ${renderUsername(currMember.user)} (${currMember.id}): You cannot act on this member`,
```suggestion
          `Failed to move ${renderUsername(currMember)} (${currMember.id}): You cannot act on this member`,
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/commands/VcmoveCmd.ts
> +          `Failed to move ${renderUsername(currMember.user)} (${currMember.id})`,
```suggestion
          `Failed to move ${renderUsername(currMember)} (${currMember.id})`,
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/functions/getUserInfoEmbed.ts
> +  const avatarURL = (member || user).displayAvatarURL();
```suggestion
  const avatarURL = (member ?? user).displayAvatarURL();
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/search.ts
> +      const fullUsername = renderUsername(member.user);
```suggestion
      const fullUsername = renderUsername(member);
```

2023-11-26 16:24 UTC, almeidx commented on backend/src/plugins/Utility/search.ts
> +      line = `${paddedId} ${renderUsername(member.user)}`;
```suggestion
      line = `${paddedId} ${renderUsername(member)}`;
```

2023-12-27 22:47 UTC, almeidx approved these changes

2024-01-27 12:36 UTC, Dragory commented
Continued in #453

2024-01-27 12:36 UTC, closed without merging